baseurl: ""
url: "https://reactiveblend.com"

# Configuración de desarrollo
dev_password: "pass1983"  # Cambiar esto
under_construction: true      # Cambiar a false cuando quieras desactivarlo

# Site settings
title: Reactive Blend Studio
email: contact@reactiveblend.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Ariel Aguilar
  pic: 1
  position: "Sfx-Music | Programmer"
  social:
  - title: x-twitter
    url: http://www.x.com/levetdev
  - title: instagram 
    url: http://www.instagram.com/ariel.bnd
  - title: envelope
    url: mailto:ariel.bnd@gmail.com

- name: Martín Ibarra
  pic: 2
  position: "2D-3D Artist | Programmer"
  social:
    - title: envelope
      url: mailto:martinibarrasm@hotmail.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: x-twitter
    url: http://www.x.com/reactiveblend
  - title: tiktok
    url: http://www.tiktok.com/@reactiveblend
  - title: instagram 
    url: http://www.instagram.com/reactiveblend
  #- title: envelope
  #  url: mailto:contact@reactiveblend.com

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty